### ISSUE TITLE
"pluck" method improvement

### ISSUE THREAD

**Issue by mcvladthegoat** [superchargejs/collections#78]
Reference: https://superchargejs.com/docs/master/collections#pluck

I'm going to add tiny feature to `.pluck()`: search by nested key. But I have one question about `key` parameter. 

Which of the two options for specifying a key is better:  `key.nested_key_1.nested_key_2` or `key[nested_key_1][nested_key_2]` ?

It seems that 2nd variant looks better because it covers more variants of `key` (for ex.: string with spaces)

**Comment by marcuspoehls** [comment]
@mcvladthegoat Thank you for tackling this improvement!

Actually, I'm leaning towards the dot-notation because it's more readable. I can see your point of object keys having spaces or dashes, like an HTTP request header `content-type`.

For me, it still feels ok to use dot-notation with spaces/dashes like `object.user-address.street`.

Are you ok with that?

**Comment by mcvladthegoat** [comment]
@marcuspoehls yes, sounds good, i'll use dot-notation :)

**Comment by marcuspoehls** [comment]
Cool, thank you!

**Comment by marcuspoehls** [comment]
@mcvladthegoat Hey Vlad, if you want and need any help, or you want to pick another brain for some thoughts, please don't hesitate to reach out :)

**Comment by mcvladthegoat** [comment]
@marcuspoehls ok, thanks for the suggestion :)

**Comment by marcuspoehls** [comment]
Closing this issue because I didn’t need the `pluck` method within the last two years. However, if you feel like this method is needed: please go ahead an open a merge request :)
